local plug = vim.fn['plug#']

plug('tpope/vim-sensible')

-- plugins
plug('tpope/vim-fugitive')
plug('vim-airline/vim-airline')
plug('vim-airline/vim-airline-themes')
plug('easymotion/vim-easymotion')
plug('junegunn/fzf', {['do'] = vim.fn['fzf#install']})
plug('Shougo/vimproc.vim', {['do'] = 'VimProcInstall' })
plug('mbbill/undotree')
plug('nvim-treesitter/nvim-treesitter', {['do'] = 'TSUpdate'})
plug('williamboman/mason.nvim', {['do'] = 'MasonUpdate'})
plug('williamboman/mason-lspconfig.nvim')
plug('neovim/nvim-lspconfig')
plug('neovim/nvim-lspconfig')
plug('hrsh7th/cmp-nvim-lsp')
plug('hrsh7th/cmp-buffer')
plug('hrsh7th/cmp-path')
plug('hrsh7th/cmp-cmdline')
plug('hrsh7th/nvim-cmp')

-- Syntaxes and Filetypes
plug('fatih/vim-go', {['do'] = 'GoUpdateBinaries'})
plug('rust-lang/rust.vim')
plug('cespare/vim-toml')
plug('prettier/vim-prettier', {['do'] = 'npm install'})
plug('pangloss/vim-javascript')
plug('mxw/vim-jsx')
plug('DeedleFake/vim-wdte')
plug('jparise/vim-graphql')
plug('LnL7/vim-nix')
plug('udalov/kotlin-vim')
plug('leafgarland/typescript-vim')
plug('peitalin/vim-jsx-typescript')
plug('Quramy/tsuquyomi')
plug('tikhomirov/vim-glsl')
plug('hashivim/vim-terraform')
plug('evanleck/vim-svelte')
plug('weakish/rcshell.vim')
plug('DeedleFake/mkfile.vim')
plug('joerdav/templ.vim')
plug('elixir-editors/vim-elixir')
plug('gleam-lang/gleam.vim')
plug('ChrisWellsWood/roc.vim')

-- Colorschemes
plug('tpope/vim-vividchalk')
plug('kristijanhusak/vim-hybrid-material')
plug('hzchirs/vim-material')
plug('junegunn/seoul256.vim')
plug('NLKNguyen/papercolor-theme')
plug('morhetz/gruvbox')
